/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Sonya7iii.glb --draco 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Sonya7iii(props) {
  const { nodes, materials } = useGLTF('3dModel/Sonya7iii.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.222, 2.205, 0.008]} scale={[2.287, 1.305, 0.563]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={nodes.Cube001_3.material} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials.Mark} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials['Material.026']} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.006']} position={[-0.103, 2.698, 0.295]} rotation={[1.571, 0, 0]} scale={0.294} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.005']} position={[0.021, 1.7, 0.116]} rotation={[1.571, 0, 0]} scale={0.465} />
      <group position={[-1.876, 1.978, 0.485]} scale={[1.397, 1, 0.085]}>
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.Screen} />
      </group>
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[-2.682, 3.207, 0.486]} rotation={[-0.493, 0, 0]} scale={[0.172, 0.059, 0.01]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Screen} position={[-1.876, 1.978, 0.485]} scale={[1.397, 1, 0.085]} />
      <group position={[0.733, 3.47, 0.039]} scale={[0.299, 0.065, 0.299]}>
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cylinder003_3.geometry} material={materials['Material.016']} />
      </group>
      <group position={[-0.442, 3.612, -0.322]} scale={[0.35, 0.074, 0.35]}>
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials.uPPER} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials.Side} />
      </group>
      <group position={[-1.678, 3.776, 1.425]} scale={[0.826, 0.423, 0.423]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials['Material.018']} />
      </group>
      <group position={[-1.775, 2.252, -1.921]} rotation={[1.571, 0, 0]}>
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Lens fitter']} />
        <mesh geometry={nodes.Cylinder002_2.geometry} material={materials.Mirror} />
      </group>
      <group position={[-1.775, 2.252, -1.921]} rotation={[1.571, 0, 0]}>
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Lens fitter']} />
        <mesh geometry={nodes.Cylinder005_2.geometry} material={materials.Border} />
      </group>
      <group position={[0.28, 2.843, -1.243]} scale={0.509}>
        <mesh geometry={nodes.Cube008.geometry} material={materials.nOISE} />
        <mesh geometry={nodes.Cube008_1.geometry} material={materials['uPPER SIDE']} />
      </group>
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.014']} position={[0.277, 3.277, -1.144]} rotation={[-0.177, 0, 0]} scale={[0.278, 0.024, 0.278]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.019']} position={[0.406, 3.105, -1.542]} rotation={[0.103, 0, 0]} scale={[0.312, 0.033, 0.141]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.017']} position={[-2.837, 3.362, 0.234]} rotation={[-0.493, 0, 0]} scale={[0.172, 0.059, 0.01]} />
      <group position={[-1.699, 2.24, -2.113]} rotation={[Math.PI / 2, 0, 0]} scale={[1.097, 0.161, 1.097]}>
        <mesh geometry={nodes.Cylinder008_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder008_2.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cylinder008_3.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder008_4.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Cylinder008_5.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Cylinder008_6.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Cylinder008_7.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Cylinder008_8.geometry} material={materials['Material.024']} />
      </group>
      
    </group>
  )
}

useGLTF.preload('3dModel/Sonya7iii.glb')
